### ISSUE TITLE
Load module task not idempotent

### ISSUE THREAD

**Issue by jamieburchell** [linux-system-roles/selinux#133]
Example config:

```
selinux_modules:
  - path: "selinux_modules/php_ptrace.pp"
    state: enabled
```

The task makes the same changes each time it runs, regardless of whether the module is already installed:

```
TASK [linux-system-roles.selinux : Create temporary directory] ***************************************************************************************************************************
changed: [example_01]

TASK [linux-system-roles.selinux : Copy module file "selinux_modules/php_ptrace.pp"] *****************************************************************************************************
changed: [example_01]

TASK [linux-system-roles.selinux : Install module with priority] *************************************************************************************************************************
skipping: [example_01]

TASK [linux-system-roles.selinux : Install module] ***************************************************************************************************************************************
changed: [example_01]

TASK [linux-system-roles.selinux : Clean temporary directory "/tmp/linux_system_role.selinux4smkzw61"] ***********************************************************************************
changed: [example_01]
```

**Comment by bachradsusi** [comment]
Since SELinux userspace release 3.4 or since RHEL 8.6, it's possible to list also installed module checksums. In case that both installed module and local file checksums are same, the role could not install module again, e.g. for zosremote.pp

~~~
# file_checksum="sha256:`/usr/libexec/selinux/hll/pp zosremote.pp | sha256sum | awk '{ print \$1;}'`"
# echo $file_checksum 
sha256:77d9792d5964f3046a6c3e24c105b73a51de67b7a0cda79783b9f175abec21e9

# module_checksum=`semodule -l --checksum | grep zosremote | awk '{ print $2; }'`
# echo $module_checksum 
sha256:77d9792d5964f3046a6c3e24c105b73a51de67b7a0cda79783b9f175abec21e9

# if [ "$module_checksum" = "$file_checksum" ]; then echo "already installed"; else semodule -i zosremote.pp; fi
already installed
~~~

**Comment by jamieburchell** [comment]
I've seen other roles handle this by keeping the source te/pp files on the remote location and only proceeding to install when the files have changed.

**Comment by bachradsusi** [comment]
The source files on the remote location would not be reliable. Between two role runs, users could use `semanage` to manage modules directly on the remote location .

**Comment by richm** [comment]
> > The source files on the remote location would not be reliable. Between two role runs, users could use `semanage` to manage modules directly on the remote location .
> 
> Should users be doing that if the modules are Ansible managed?

No, they shouldn't.  If a particular selinux module is managed by Ansible, then it is fully managed by Ansible, and if a user makes a change outside of Ansible, they should expect that change will be wiped out and replaced the next time Ansible is run.

**Comment by bachradsusi** [comment]
Since SELinux userspace release [20150202](https://lore.kernel.org/selinux/54CF9F03.8040604@tresys.com/#r) - 2.4 released in 2015:

- a module name always corresponds to the file name. e.g. `mylocalmodule.pp` -> *mylocalmodule*, `anothermodule.cil` -> `anothermodule`
- all .pp modules are converted to cil and the system policy is built from these .cil files
- it's possible to convert .pp files to .cil using `/usr/libexec/selinux/hll/pp`

Therefore `semodule -l --checksum` uses cil version of modules for counting a hash 

The code above was just an example to show how  checksums in selinux module store works and how to use them. In this project it should be implemented in python using libsemanage python bindings and `hashlib`

I can create a patch but I need to finish my other priorities first.

**Comment by bachradsusi** [comment]
I've started with the work at https://github.com/bachradsusi/linux-system-roles-selinux/tree/local_semodule - see https://github.com/linux-system-roles/selinux/compare/master...bachradsusi:linux-system-roles-selinux:local_semodule for initial implementation of local_semodule which should manage modules. At this moment, it implements only module installation.

**Comment by bachradsusi** [comment]
@richm Could you please take a look at my branch and tell me whether this approach is reasonable from Ansible and ansible roles point of view?

**Comment by richm** [comment]
> @richm Could you please take a look at my branch and tell me whether this approach is reasonable from Ansible and ansible roles point of view?

Yes, lgtm.

**Comment by jamieburchell** [comment]
Thank you! It looks like the role will still create a temp directory and copy the file each time it is run though.

**Comment by richm** [comment]
> Thank you! It looks like the role will still create a temp directory and copy the file each time it is run though.

How could we mitigate that?  By generating the checksum on the controller (or wherever the source file is)?

**Comment by jamieburchell** [comment]
The only thing I can think of is creating a permanent location on the remote to copy the file to. Once it's there, it won't be copied again unless its content is changed. I guess it could be configurable to either use a specific path or a temporary location.

**Comment by richm** [comment]
> The only thing I can think of is creating a permanent location on the remote to copy the file to. Once it's there, it won't be copied again unless its content is changed. I guess it could be configurable to either use a specific path or a temporary location.

OK.  Please open a separate issue or PR for that.

**Comment by jamieburchell** [comment]
Do I need to open a new issue when this behaviour was already described originally?

No problem if so, just not sure if it was missed from the original report.

**Comment by richm** [comment]
> Do I need to open a new issue when this behaviour was already described originally?
> 
> No problem if so, just not sure if it was missed from the original report.

So are you saying that the issue of module management idempotency was not solved, because you still see
```
TASK [linux-system-roles.selinux : Create temporary directory] ***************************************************************************************************************************
changed: [example_01]

TASK [linux-system-roles.selinux : Copy module file "selinux_modules/php_ptrace.pp"] *****************************************************************************************************
changed: [example_01]
```
and these report `changed: true` even if nothing needed to be changed, so even though the module management part is idempotent, the role is still not idempotent because it reports `changed: true` even though nothing was really changed?

**Comment by jamieburchell** [comment]
Exactly that, and the cleanup of the temp directory is included in that.
