### ISSUE TITLE
Incorrect/incomplete information in README.md:

### ISSUE THREAD

**Issue by captainjs** [linux-system-roles/selinux#45]
Hi,
Versions:
rhel-system-roles 1.0-5 el8
RHEL8.0 

When checking the file:
/usr/share/ansible/roles/linux-system-roles.selinux/README.md, it shows:

_Usage
The general usage is demonstrated in selinux-playbook.yml playbook._

1) It should say where that file is located.

2) There is no "selinux-playbook.yml", the file is actually called "example-selinux-playbook.yml":
 /usr/share/doc/rhel-system-roles/selinux/example-selinux-playbook.yml

Can you please fix that?
Thanks,

**Comment by pcahyna** [comment]
Hello, thanks for the report.

> _Usage The general usage is demonstrated in selinux-playbook.yml playbook._
> 
>     1. It should say where that file is located.

This may be a bit problematic, because it depends on where the distribution package puts those files (this could be said in the distribution documentation). Or we could say "in the same directory as this README".

>     2. There is no "selinux-playbook.yml", the file is actually called "example-selinux-playbook.yml":
>        /usr/share/doc/rhel-system-roles/selinux/example-selinux-playbook.yml

Indeed, the names of example file are not the same in the released package and this is not ideal. @mikedep333 what do you think?

By the way this should be tracked in the RHEL bugzilla as it is not so much a problem with the upstream code.

**Comment by mikedep333** [comment]
@pcahyna @captainjs 

I think we should put these under a new subfolder, without renaming them
`/usr/share/ansible/roles/linux-system-roles.selinux/examples/`
 (And document its path when installed as an RPM.)

I say this because we have RPM build (%install) logic like:

`mv $RPM_BUILD_ROOT%{_datadir}/ansible/roles/%{roleprefix}network/examples/inventory \ $RPM_BUILD_ROOT%{_pkgdocdir}/network/example-inventory`

And thus for the example of the network role, we have a giant list of files in 1 folder like:

```
/usr/share/doc/rhel-system-roles-1.0/kdump/COPYING
/usr/share/doc/rhel-system-roles-1.0/kdump/README.md
/usr/share/doc/rhel-system-roles-1.0/network/LICENSE
/usr/share/doc/rhel-system-roles-1.0/network/README.md
/usr/share/doc/rhel-system-roles-1.0/network/example-bond-with-vlan-playbook.yml
/usr/share/doc/rhel-system-roles-1.0/network/example-bridge-with-vlan-playbook.yml
/usr/share/doc/rhel-system-roles-1.0/network/example-down-profile-playbook.yml
/usr/share/doc/rhel-system-roles-1.0/network/example-eth-simple-auto-playbook.yml
/usr/share/doc/rhel-system-roles-1.0/network/example-eth-with-vlan-playbook.yml
/usr/share/doc/rhel-system-roles-1.0/network/example-infiniband-playbook.yml
/usr/share/doc/rhel-system-roles-1.0/network/example-inventory
/usr/share/doc/rhel-system-roles-1.0/network/example-macvlan-playbook.yml
/usr/share/doc/rhel-system-roles-1.0/network/example-remove-profile-playbook.yml
/usr/share/doc/rhel-system-roles-1.0/network/example-inventory

```
